// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/KeyValueResponse.proto

package protobuf;

public final class KeyValueResponse {
  private KeyValueResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KVResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.KVResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 errCode = 1;</code>
     */
    int getErrCode();

    /**
     * <code>bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>int32 pid = 3;</code>
     */
    int getPid();

    /**
     * <code>int32 version = 4;</code>
     */
    int getVersion();

    /**
     * <code>int32 overloadWaitTime = 5;</code>
     */
    int getOverloadWaitTime();

    /**
     * <code>int32 membershipCount = 6;</code>
     */
    int getMembershipCount();
  }
  /**
   * Protobuf type {@code protobuf.KVResponse}
   */
  public  static final class KVResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.KVResponse)
      KVResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KVResponse.newBuilder() to construct.
    private KVResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KVResponse() {
      errCode_ = 0;
      value_ = com.google.protobuf.ByteString.EMPTY;
      pid_ = 0;
      version_ = 0;
      overloadWaitTime_ = 0;
      membershipCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KVResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              errCode_ = input.readUInt32();
              break;
            }
            case 18: {

              value_ = input.readBytes();
              break;
            }
            case 24: {

              pid_ = input.readInt32();
              break;
            }
            case 32: {

              version_ = input.readInt32();
              break;
            }
            case 40: {

              overloadWaitTime_ = input.readInt32();
              break;
            }
            case 48: {

              membershipCount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.KeyValueResponse.internal_static_protobuf_KVResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.KeyValueResponse.internal_static_protobuf_KVResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.KeyValueResponse.KVResponse.class, protobuf.KeyValueResponse.KVResponse.Builder.class);
    }

    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <code>uint32 errCode = 1;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int PID_FIELD_NUMBER = 3;
    private int pid_;
    /**
     * <code>int32 pid = 3;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_;
    /**
     * <code>int32 version = 4;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int OVERLOADWAITTIME_FIELD_NUMBER = 5;
    private int overloadWaitTime_;
    /**
     * <code>int32 overloadWaitTime = 5;</code>
     */
    public int getOverloadWaitTime() {
      return overloadWaitTime_;
    }

    public static final int MEMBERSHIPCOUNT_FIELD_NUMBER = 6;
    private int membershipCount_;
    /**
     * <code>int32 membershipCount = 6;</code>
     */
    public int getMembershipCount() {
      return membershipCount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCode_ != 0) {
        output.writeUInt32(1, errCode_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(2, value_);
      }
      if (pid_ != 0) {
        output.writeInt32(3, pid_);
      }
      if (version_ != 0) {
        output.writeInt32(4, version_);
      }
      if (overloadWaitTime_ != 0) {
        output.writeInt32(5, overloadWaitTime_);
      }
      if (membershipCount_ != 0) {
        output.writeInt32(6, membershipCount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errCode_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (pid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pid_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      if (overloadWaitTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, overloadWaitTime_);
      }
      if (membershipCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, membershipCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.KeyValueResponse.KVResponse)) {
        return super.equals(obj);
      }
      protobuf.KeyValueResponse.KVResponse other = (protobuf.KeyValueResponse.KVResponse) obj;

      boolean result = true;
      result = result && (getErrCode()
          == other.getErrCode());
      result = result && getValue()
          .equals(other.getValue());
      result = result && (getPid()
          == other.getPid());
      result = result && (getVersion()
          == other.getVersion());
      result = result && (getOverloadWaitTime()
          == other.getOverloadWaitTime());
      result = result && (getMembershipCount()
          == other.getMembershipCount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + PID_FIELD_NUMBER;
      hash = (53 * hash) + getPid();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + OVERLOADWAITTIME_FIELD_NUMBER;
      hash = (53 * hash) + getOverloadWaitTime();
      hash = (37 * hash) + MEMBERSHIPCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getMembershipCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.KeyValueResponse.KVResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.KeyValueResponse.KVResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.KeyValueResponse.KVResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.KeyValueResponse.KVResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.KVResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.KVResponse)
        protobuf.KeyValueResponse.KVResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.KeyValueResponse.internal_static_protobuf_KVResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.KeyValueResponse.internal_static_protobuf_KVResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.KeyValueResponse.KVResponse.class, protobuf.KeyValueResponse.KVResponse.Builder.class);
      }

      // Construct using protobuf.KeyValueResponse.KVResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errCode_ = 0;

        value_ = com.google.protobuf.ByteString.EMPTY;

        pid_ = 0;

        version_ = 0;

        overloadWaitTime_ = 0;

        membershipCount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.KeyValueResponse.internal_static_protobuf_KVResponse_descriptor;
      }

      @java.lang.Override
      public protobuf.KeyValueResponse.KVResponse getDefaultInstanceForType() {
        return protobuf.KeyValueResponse.KVResponse.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.KeyValueResponse.KVResponse build() {
        protobuf.KeyValueResponse.KVResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.KeyValueResponse.KVResponse buildPartial() {
        protobuf.KeyValueResponse.KVResponse result = new protobuf.KeyValueResponse.KVResponse(this);
        result.errCode_ = errCode_;
        result.value_ = value_;
        result.pid_ = pid_;
        result.version_ = version_;
        result.overloadWaitTime_ = overloadWaitTime_;
        result.membershipCount_ = membershipCount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.KeyValueResponse.KVResponse) {
          return mergeFrom((protobuf.KeyValueResponse.KVResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.KeyValueResponse.KVResponse other) {
        if (other == protobuf.KeyValueResponse.KVResponse.getDefaultInstance()) return this;
        if (other.getErrCode() != 0) {
          setErrCode(other.getErrCode());
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getPid() != 0) {
          setPid(other.getPid());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getOverloadWaitTime() != 0) {
          setOverloadWaitTime(other.getOverloadWaitTime());
        }
        if (other.getMembershipCount() != 0) {
          setMembershipCount(other.getMembershipCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.KeyValueResponse.KVResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.KeyValueResponse.KVResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errCode_ ;
      /**
       * <code>uint32 errCode = 1;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>uint32 errCode = 1;</code>
       */
      public Builder setErrCode(int value) {
        
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 errCode = 1;</code>
       */
      public Builder clearErrCode() {
        
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>int32 pid = 3;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>int32 pid = 3;</code>
       */
      public Builder setPid(int value) {
        
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pid = 3;</code>
       */
      public Builder clearPid() {
        
        pid_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 4;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 4;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 4;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int overloadWaitTime_ ;
      /**
       * <code>int32 overloadWaitTime = 5;</code>
       */
      public int getOverloadWaitTime() {
        return overloadWaitTime_;
      }
      /**
       * <code>int32 overloadWaitTime = 5;</code>
       */
      public Builder setOverloadWaitTime(int value) {
        
        overloadWaitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 overloadWaitTime = 5;</code>
       */
      public Builder clearOverloadWaitTime() {
        
        overloadWaitTime_ = 0;
        onChanged();
        return this;
      }

      private int membershipCount_ ;
      /**
       * <code>int32 membershipCount = 6;</code>
       */
      public int getMembershipCount() {
        return membershipCount_;
      }
      /**
       * <code>int32 membershipCount = 6;</code>
       */
      public Builder setMembershipCount(int value) {
        
        membershipCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 membershipCount = 6;</code>
       */
      public Builder clearMembershipCount() {
        
        membershipCount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.KVResponse)
    }

    // @@protoc_insertion_point(class_scope:protobuf.KVResponse)
    private static final protobuf.KeyValueResponse.KVResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.KeyValueResponse.KVResponse();
    }

    public static protobuf.KeyValueResponse.KVResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KVResponse>
        PARSER = new com.google.protobuf.AbstractParser<KVResponse>() {
      @java.lang.Override
      public KVResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KVResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KVResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KVResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.KeyValueResponse.KVResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_KVResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_KVResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034proto/KeyValueResponse.proto\022\010protobuf" +
      "\"}\n\nKVResponse\022\017\n\007errCode\030\001 \001(\r\022\r\n\005value" +
      "\030\002 \001(\014\022\013\n\003pid\030\003 \001(\005\022\017\n\007version\030\004 \001(\005\022\030\n\020" +
      "overloadWaitTime\030\005 \001(\005\022\027\n\017membershipCoun" +
      "t\030\006 \001(\005B\rZ\013pb/protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_KVResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_KVResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_KVResponse_descriptor,
        new java.lang.String[] { "ErrCode", "Value", "Pid", "Version", "OverloadWaitTime", "MembershipCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
